### ISSUE TITLE
Crashes on download and weird update behaviour

### ISSUE THREAD

**Issue by Muzer** [DownloadMii/DownloadMii#25] opened 2015-02-07 04:07 UTC
I'm running the latest Ninjhax (1.1) with 4.5.0-10E. Whenever I run the latest stable version of this app (1.0.5.8), I first encounter a screen telling me that the app is version 0.0.0.0 and that I should upgrade to 1.0.5.8. If I agree to upgrade, the screen freezes and I eventually get returned to the home menu with an error message. If I disagree, the app works until I come to download something, at which point the same thing occurs (freeze, then dump to home menu).

I installed it from the website by unzipping directly onto the SD.

Any ideas?

**Comment by celcodioc** [comment] 2015-02-07 13:26
Duplicate of #24, please follow the discussion there :)

**Closed by celcodioc** 2015-02-07 13:26 UTC
